package redact

import "regexp"

type SecretPattern struct {
	ID            string
	Category      string
	Title         string
	Pattern       string
	Keywords      []string
	CaseInsensitive bool
	ExcludeWords  []string // Captured values containing these words are skipped (false-positive prevention)
	compiled      *regexp.Regexp
}

var BuiltinPatterns = []SecretPattern{
	{ID: "sourcegraph-access-token-v3", Category: "sourcegraph", Title: "Sourcegraph Access Token (v3)", Pattern: `(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40})`, Keywords: []string{"sgp_"}},
	{ID: "sourcegraph-access-token-v2", Category: "sourcegraph", Title: "Sourcegraph Access Token (v2, deprecated)", Pattern: `(sgp_[a-fA-F0-9]{40})`, Keywords: []string{"sgp_"}},
	{ID: "sourcegraph-dotcom-user-gateway", Category: "sourcegraph", Title: "Sourcegraph Dotcom User Gateway Access Token", Pattern: `(sgd_[a-fA-F0-9]{64})`, Keywords: []string{"sgd_"}},
	{ID: "sourcegraph-license-key", Category: "sourcegraph", Title: "Sourcegraph License Key Token", Pattern: `(slk_[a-fA-F0-9]{64})`, Keywords: []string{"slk_"}},
	{ID: "sourcegraph-enterprise-subscription", Category: "sourcegraph", Title: "Sourcegraph Enterprise subscription Token", Pattern: `(sgs_[a-fA-F0-9]{64})`, Keywords: []string{"sgs_"}},
	{ID: "sourcegraph-amp", Category: "sourcegraph", Title: "Sourcegraph Amp Access Token", Pattern: `(sgamp_user_[A-Z0-9]{26}_[a-f0-9]{64})`, Keywords: []string{"sgamp_user_"}},
	{ID: "sourcegraph-amp-auth-bypass", Category: "sourcegraph", Title: "Sourcegraph Amp Auth Bypass Token", Pattern: `(sgamp_user_auth-bypass_[a-zA-Z0-9_-]+)`, Keywords: []string{"sgamp_user_auth-bypass_"}},
	{ID: "sourcegraph-workspace-token", Category: "sourcegraph", Title: "Sourcegraph Workspace Access Token", Pattern: `(sgp_ws[a-fA-F0-9]{32}_[a-fA-F0-9]{40})`, Keywords: []string{"sgp_ws"}},
	{ID: "github-pat", Category: "github", Title: "GitHub Personal Access Token", Pattern: `(ghp_[0-9a-zA-Z]{36})`, Keywords: []string{"ghp_"}},
	{ID: "github-oauth", Category: "github", Title: "GitHub OAuth Access Token", Pattern: `(gho_[0-9a-zA-Z]{36})`, Keywords: []string{"gho_"}},
	{ID: "github-app-token", Category: "github", Title: "GitHub App Token", Pattern: `((ghu|ghs)_[0-9a-zA-Z]{36})`, Keywords: []string{"ghu_", "ghs_"}},
	{ID: "github-refresh-token", Category: "github", Title: "GitHub Refresh Token", Pattern: `(ghr_[0-9a-zA-Z]{76})`, Keywords: []string{"ghr_"}},
	{ID: "github-fine-grained-pat", Category: "github", Title: "GitHub Fine-grained personal access tokens", Pattern: `(github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})`, Keywords: []string{"github_pat_"}},
	{ID: "gitlab-pat", Category: "gitlab", Title: "GitLab Personal Access Token", Pattern: `(glpat-[0-9a-zA-Z_-]{20})`, Keywords: []string{"glpat-"}},
	{ID: "bitbucket-pat", Category: "bitbucket", Title: "Bitbucket Personal Access Token", Pattern: `(bbpat-[A-Za-z0-9]{20,200})`, Keywords: []string{"bbpat-"}},
	{ID: "bitbucket-repo-access-token", Category: "bitbucket", Title: "Bitbucket Repository Access Token", Pattern: `(bbrat-[A-Za-z0-9]{20,200})`, Keywords: []string{"bbrat-"}},
	{ID: "bitbucket-dc-http-token", Category: "bitbucket", Title: "Bitbucket DC/Server HTTP Access Token", Pattern: `(?:[a-z0-9_ .,-]{0,25}bitbucket[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([A-Za-z0-9+/]{40,80}={0,2})['"]`, Keywords: []string{"bitbucket"}},
	{ID: "aws-access-key-id", Category: "aws", Title: "AWS Access Key ID", Pattern: `((A3T[A-Z0-9]|AKIA|ASIA)[A-Z0-9]{16})`, Keywords: []string{"A3T", "AKIA", "ASIA"}},
	{ID: "hugging-face-access-token", Category: "huggingface", Title: "Hugging Face Access Token", Pattern: `(hf_[A-Za-z0-9]{34,40})`, Keywords: []string{"hf_"}},
	{ID: "private-key", Category: "asymmetric-private-key", Title: "Asymmetric Private Key", Pattern: `-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY(?:\sBLOCK)?\s*?-----\s*([A-Za-z0-9=+/\s]+)\s*-----\s*?END[ A-Z0-9_-]*?\sPRIVATE KEY(?:\sBLOCK)?\s*?-----`, Keywords: []string{"-----"}, CaseInsensitive: true},
	{ID: "shopify-token", Category: "shopify", Title: "Shopify token", Pattern: `(shp(ss|at|ca|pa)_[a-fA-F0-9]{32})`, Keywords: []string{"shpss_", "shpat_", "shpca_", "shppa_"}},
	{ID: "slack-access-token", Category: "slack", Title: "Slack token", Pattern: `((xox[baoprs]-|xapp-|xwfp-)([0-9a-zA-Z-]{10,100}))`, Keywords: []string{"xoxb-", "xoxa-", "xoxp-", "xoxr-", "xoxs-", "xoxo-", "xapp-", "xwfp-"}},
	{ID: "slack-config-refresh-token", Category: "slack", Title: "Slack config refresh token", Pattern: `(xoxe-\d-[a-zA-Z0-9]{146})`, CaseInsensitive: true, Keywords: []string{"xoxe-"}},
	{ID: "slack-config-access-token", Category: "slack", Title: "Slack config access token", Pattern: `(xoxe\.xox[bp]-\d-[A-Z0-9]{163,166})`, CaseInsensitive: true, Keywords: []string{"xoxe.xoxb-", "xoxe.xoxp-"}},
	{ID: "slack-web-hook", Category: "slack", Title: "Slack Webhook", Pattern: `(https://hooks\.slack\.com/(services|triggers|workflows)/[A-Za-z0-9+/]{43,56})`, CaseInsensitive: true, Keywords: []string{"hooks.slack.com"}},
	{ID: "stripe-secret-token", Category: "stripe", Title: "Stripe Secret Key", Pattern: `(sk_(test|live)_[0-9a-z]{10,99})`, Keywords: []string{"sk_test_", "sk_live_"}, CaseInsensitive: true},
	{ID: "supabase-service-key", Category: "supabase", Title: "Supabase Service Key", Pattern: `(sbp_[a-fA-F0-9]{40})`, Keywords: []string{"sbp_"}},
	{ID: "pypi-upload-token", Category: "pypi", Title: "PyPI upload token", Pattern: `(pypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,1000})`, Keywords: []string{"pypi-AgEIcHlwaS5vcmc"}},
	{ID: "cloudflare-api-token", Category: "unknown", Title: "Cloudflare API Token", Pattern: `\b(cfut_[A-Za-z0-9]{48})\b`, Keywords: []string{"cfut_"}},
	{ID: "e2b-api-key", Category: "unknown", Title: "E2B API Key", Pattern: `\b(e2b_[a-f0-9]{40})\b`, Keywords: []string{"e2b_"}},
	{ID: "google-api-key", Category: "google", Title: "Google API Key", Pattern: `\b(AIza[0-9A-Za-z_-]{35,40})\b`, Keywords: []string{"AIza"}},
	{ID: "heroku-api-key", Category: "heroku", Title: "Heroku API Key", Pattern: `(?:heroku[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](\d[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})['"]`, Keywords: []string{"heroku"}, CaseInsensitive: true},
	{ID: "twilio-api-key", Category: "twilio", Title: "Twilio API Key", Pattern: `(SK[0-9a-fA-F]{32})`, Keywords: []string{"SK"}},
	{ID: "age-secret-key", Category: "age", Title: "Age secret key", Pattern: `(AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58})`, Keywords: []string{"AGE-SECRET-KEY-1"}},
	{ID: "jwt-token", Category: "jwt", Title: "JWT token", Pattern: `(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9/\\_-]{17,}\.(?:[a-zA-Z0-9/\\_-]{10,}={0,2})?)`, Keywords: []string{".eyJ"}},
	{ID: "npm-access-token", Category: "npm", Title: "npm access token", Pattern: `(npm_[a-z0-9]{36})`, Keywords: []string{"npm_"}, CaseInsensitive: true},
	{ID: "sendgrid-api-token", Category: "sendgrid", Title: "SendGrid API token", Pattern: `(SG\.[a-z0-9_.-]{66})`, Keywords: []string{"SG."}, CaseInsensitive: true},
	{ID: "aws-secret-access-key", Category: "aws", Title: "AWS Secret Access Key", Pattern: `(aws[_-]secret[_-]access[_-]key[_-][A-Za-z0-9/+=]{40})`, Keywords: []string{"key"}, CaseInsensitive: true},
	{ID: "dockerconfig-secret", Category: "docker", Title: "Dockerconfig secret exposed", Pattern: `((\.dockerconfigjson|dockercfg):\s*\|*\s*((ey|ew)+[A-Za-z0-9/+=]+))`, Keywords: []string{"dockerc"}, CaseInsensitive: true},
	{ID: "linear-api-token", Category: "linear", Title: "Linear API token", Pattern: `(lin_api_[a-z0-9]{40})`, Keywords: []string{"lin_api_"}, CaseInsensitive: true},
	{ID: "sendinblue-api-token", Category: "sendinblue", Title: "Sendinblue API token", Pattern: `(xkeysib-[a-f0-9]{64}-[a-z0-9]{16})`, Keywords: []string{"xkeysib-"}, CaseInsensitive: true},
	{ID: "planetscale-api-token", Category: "planetscale", Title: "PlanetScale API token", Pattern: `(pscale_tkn_[a-z0-9_.-]{43})`, Keywords: []string{"pscale_tkn_"}, CaseInsensitive: true},
	{ID: "doppler-api-token", Category: "doppler", Title: "Doppler API token", Pattern: `(dp\.pt\.[a-z0-9]{43})`, Keywords: []string{"dp.pt."}, CaseInsensitive: true},
	{ID: "discord-api-token", Category: "discord", Title: "Discord API key", Pattern: `(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{64})['"]`, Keywords: []string{"discord"}, CaseInsensitive: true},
	{ID: "pulumi-api-token", Category: "pulumi", Title: "Pulumi API token", Pattern: `(pul-[a-f0-9]{40})`, Keywords: []string{"pul-"}},
	{ID: "postman-api-token", Category: "postman", Title: "Postman API token", Pattern: `(PMAK-[a-f0-9]{24}-[a-f0-9]{34})`, Keywords: []string{"PMAK-"}, CaseInsensitive: true},
	{ID: "facebook-token", Category: "facebook", Title: "Facebook token", Pattern: `(?:facebook[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`, Keywords: []string{"facebook"}, CaseInsensitive: true},
	{ID: "twitter-token", Category: "twitter", Title: "Twitter token", Pattern: `(?:twitter[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{35,44})['"]`, Keywords: []string{"twitter"}, CaseInsensitive: true},
	{ID: "adobe-client-id", Category: "adobe", Title: "Adobe Client ID (Oauth Web)", Pattern: `(?:adobe[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`, Keywords: []string{"adobe"}, CaseInsensitive: true},
	{ID: "adobe-client-secret", Category: "adobe", Title: "Adobe Client Secret", Pattern: `(p8e-[a-z0-9]{32})`, Keywords: []string{"p8e-"}, CaseInsensitive: true},
	{ID: "alibaba-access-key-id", Category: "alibaba", Title: "Alibaba AccessKey ID", Pattern: `((LTAI)[a-z0-9]{20})`, Keywords: []string{"LTAI"}, CaseInsensitive: true},
	{ID: "alibaba-secret-key", Category: "alibaba", Title: "Alibaba Secret Key", Pattern: `(?:alibaba[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]`, Keywords: []string{"alibaba"}, CaseInsensitive: true},
	{ID: "asana-client-id", Category: "asana", Title: "Asana Client ID", Pattern: `(?:asana[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{16})['"]`, Keywords: []string{"asana"}, CaseInsensitive: true},
	{ID: "asana-client-secret", Category: "asana", Title: "Asana Client Secret", Pattern: `(?:asana[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{32})['"]`, Keywords: []string{"asana"}, CaseInsensitive: true},
	{ID: "atlassian-api-token", Category: "atlassian", Title: "Atlassian API token", Pattern: `(?:atlassian[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{24})['"]`, Keywords: []string{"atlassian"}, CaseInsensitive: true},
	{ID: "beamer-api-token", Category: "beamer", Title: "Beamer API token", Pattern: `(?:beamer[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](b_[a-z0-9=_-]{44})['"]`, Keywords: []string{"beamer"}, CaseInsensitive: true},
	{ID: "buildkite-agent-token", Category: "buildkite", Title: "Buildkite API Token V2", Pattern: `(bkua_[a-fA-F0-9]{40})`, Keywords: []string{"bkua_"}},
	{ID: "clojars-api-token", Category: "clojars", Title: "Clojars API token", Pattern: `(CLOJARS_[a-z0-9]{60})`, Keywords: []string{"CLOJARS_"}, CaseInsensitive: true},
	{ID: "contentful-delivery-api-token", Category: "contentful-delivery", Title: "Contentful delivery API token", Pattern: `(?:contentful[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{43})['"]`, Keywords: []string{"contentful"}, CaseInsensitive: true},
	{ID: "databricks-api-token", Category: "databricks", Title: "Databricks API token", Pattern: `(dapi[a-h0-9]{32})`, Keywords: []string{"dapi"}},
	{ID: "discord-client-id", Category: "discord", Title: "Discord client ID", Pattern: `(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{18})['"]`, Keywords: []string{"discord"}, CaseInsensitive: true},
	{ID: "discord-client-secret", Category: "discord", Title: "Discord client secret", Pattern: `(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{32})['"]`, Keywords: []string{"discord"}, CaseInsensitive: true},
	{ID: "dropbox-api-secret", Category: "dropbox", Title: "Dropbox API secret/key", Pattern: `(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{15})['"]`, Keywords: []string{"dropbox"}, CaseInsensitive: true},
	{ID: "dropbox-short-lived-api-token", Category: "dropbox", Title: "Dropbox short lived API token", Pattern: `(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](sl\.[a-z0-9=_-]{135})['"]`, Keywords: []string{"dropbox"}, CaseInsensitive: true},
	{ID: "dropbox-long-lived-api-token", Category: "dropbox", Title: "Dropbox long lived API token", Pattern: `(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9_=-]{43})['"]`, Keywords: []string{"dropbox"}, CaseInsensitive: true},
	{ID: "duffel-api-token", Category: "duffel", Title: "Duffel API token", Pattern: `(duffel_(test|live)_[a-z0-9_-]{43})`, Keywords: []string{"duffel_test_", "duffel_live_"}, CaseInsensitive: true},
	{ID: "dynatrace-api-token", Category: "dynatrace", Title: "Dynatrace API token", Pattern: `(dt0c01\.[a-z0-9]{24}\.[a-z0-9]{64})`, Keywords: []string{"dt0c01."}, CaseInsensitive: true},
	{ID: "easypost-api-token", Category: "easypost", Title: "EasyPost API token", Pattern: `(EZ[AT]K[a-z0-9]{54})`, Keywords: []string{"EZAK", "EZAT"}, CaseInsensitive: true},
	{ID: "fastly-api-token", Category: "fastly", Title: "Fastly API token", Pattern: `(?:fastly[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{32})['"]`, Keywords: []string{"fastly"}, CaseInsensitive: true},
	{ID: "finicity-client-secret", Category: "finicity", Title: "Finicity client secret", Pattern: `(?:finicity[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{20})['"]`, Keywords: []string{"finicity"}, CaseInsensitive: true},
	{ID: "finicity-api-token", Category: "finicity", Title: "Finicity API token", Pattern: `(?:finicity[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`, Keywords: []string{"finicity"}, CaseInsensitive: true},
	{ID: "flutterwave-public-key", Category: "flutterwave", Title: "Flutterwave public/secret key", Pattern: `(FLW(PUB|SEC)K_TEST-[a-h0-9]{32}-X)`, Keywords: []string{"FLWSECK_TEST-", "FLWPUBK_TEST-"}, CaseInsensitive: true},
	{ID: "flutterwave-enc-key", Category: "flutterwave", Title: "Flutterwave encrypted key", Pattern: `(FLWSECK_TEST[a-h0-9]{12})`, Keywords: []string{"FLWSECK_TEST"}},
	{ID: "frameio-api-token", Category: "frameio", Title: "Frame.io API token", Pattern: `(fio-u-[a-z0-9_=-]{64})`, Keywords: []string{"fio-u-"}, CaseInsensitive: true},
	{ID: "gocardless-api-token", Category: "gocardless", Title: "GoCardless API token", Pattern: `(live_[a-z0-9_=-]{40})`, Keywords: []string{"live_"}, CaseInsensitive: true},
	{ID: "grafana-api-token", Category: "grafana", Title: "Grafana API token", Pattern: `(eyJrIjoi[a-z0-9_=-]{72,92})`, Keywords: []string{"eyJrIjoi"}, CaseInsensitive: true},
	{ID: "hashicorp-tf-api-token", Category: "hashicorp", Title: "HashiCorp Terraform user/org API token", Pattern: `([a-z0-9]{14}\.atlasv1\.[a-z0-9_=-]{60,70})`, Keywords: []string{"atlasv1."}, CaseInsensitive: true},
	{ID: "hubspot-api-token", Category: "hubspot", Title: "HubSpot API token", Pattern: `(?:hubspot[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`, Keywords: []string{"hubspot"}, CaseInsensitive: true},
	{ID: "intercom-api-token", Category: "intercom", Title: "Intercom API token", Pattern: `(?:intercom[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_]{60})['"]`, Keywords: []string{"intercom"}, CaseInsensitive: true},
	{ID: "intercom-client-secret", Category: "intercom", Title: "Intercom client secret/ID", Pattern: `(?:intercom[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`, Keywords: []string{"intercom"}, CaseInsensitive: true},
	{ID: "ionic-api-token", Category: "ionic", Title: "Ionic API token", Pattern: `(?:ionic[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](ion_[a-z0-9]{42})['"]`, Keywords: []string{"ionic"}, CaseInsensitive: true},
	{ID: "linear-client-secret", Category: "linear", Title: "Linear client secret/ID", Pattern: `(?:linear[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`, Keywords: []string{"linear"}, CaseInsensitive: true},
	{ID: "lob-api-key", Category: "lob", Title: "Lob API Key", Pattern: `(?:lob[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((live|test)_[a-f0-9]{35})['"]`, Keywords: []string{"lob"}, CaseInsensitive: true},
	{ID: "mailchimp-api-key", Category: "mailchimp", Title: "Mailchimp API key", Pattern: `(?:mailchimp[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32}-us20)['"]`, Keywords: []string{"mailchimp"}, CaseInsensitive: true},
	{ID: "mailgun-token", Category: "mailgun", Title: "Mailgun private API token", Pattern: `(?:mailgun[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((pub)?key-[a-f0-9]{32})['"]`, Keywords: []string{"mailgun"}, CaseInsensitive: true},
	{ID: "mailgun-signing-key", Category: "mailgun", Title: "Mailgun webhook signing key", Pattern: `(?:mailgun[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})['"]`, Keywords: []string{"mailgun"}, CaseInsensitive: true},
	{ID: "mapbox-api-token", Category: "mapbox", Title: "Mapbox API token", Pattern: `(pk\.[a-z0-9]{60}\.[a-z0-9]{22})`, Keywords: []string{"pk."}, CaseInsensitive: true},
	{ID: "messagebird-api-token", Category: "messagebird", Title: "MessageBird API token", Pattern: `(?:messagebird[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{25})['"]`, Keywords: []string{"messagebird"}, CaseInsensitive: true},
	{ID: "messagebird-client-id", Category: "messagebird", Title: "MessageBird API client ID", Pattern: `(?:messagebird[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`, Keywords: []string{"messagebird"}, CaseInsensitive: true},
	{ID: "new-relic-user-api-key", Category: "newrelic", Title: "New Relic user API Key", Pattern: `(NRAK-[A-Z0-9]{27})`, Keywords: []string{"NRAK-"}},
	{ID: "new-relic-user-api-id", Category: "newrelic", Title: "New Relic user API ID", Pattern: `(?:newrelic[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([A-Z0-9]{64})['"]`, Keywords: []string{"newrelic"}, CaseInsensitive: true},
	{ID: "new-relic-browser-api-token", Category: "newrelic", Title: "New Relic ingest browser API token", Pattern: `(NRJS-[a-f0-9]{19})`, Keywords: []string{"NRJS-"}},
	{ID: "planetscale-password", Category: "planetscale", Title: "PlanetScale password", Pattern: `(pscale_pw_[a-z0-9_.-]{43})`, Keywords: []string{"pscale_pw_"}, CaseInsensitive: true},
	{ID: "private-packagist-token", Category: "private-packagist", Title: "Private Packagist token", Pattern: `(packagist_[ou][ru]t_[a-f0-9]{68})`, Keywords: []string{"packagist_uut_", "packagist_ort_", "packagist_out_"}, CaseInsensitive: true},
	{ID: "rubygems-api-token", Category: "rubygems", Title: "Rubygem API token", Pattern: `(rubygems_[a-f0-9]{48})`, Keywords: []string{"rubygems_"}},
	{ID: "shippo-api-token", Category: "shippo", Title: "Shippo API token", Pattern: `(shippo_(live|test)_[a-f0-9]{40})`, Keywords: []string{"shippo_live_", "shippo_test_"}},
	{ID: "linkedin-client-secret", Category: "linkedin", Title: "LinkedIn Client secret", Pattern: `(?:linkedin[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z]{16})['"]`, Keywords: []string{"linkedin"}, CaseInsensitive: true},
	{ID: "linkedin-client-id", Category: "linkedin", Title: "LinkedIn Client ID", Pattern: `(?:linkedin[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{14})['"]`, Keywords: []string{"linkedin"}, CaseInsensitive: true},
	{ID: "twitch-api-token", Category: "twitch", Title: "Twitch API token", Pattern: `(?:twitch[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]`, Keywords: []string{"twitch"}, CaseInsensitive: true},
	{ID: "typeform-api-token", Category: "typeform", Title: "Typeform API token", Pattern: `(?:typeform[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}(tfp_[a-z0-9_.=-]{59})`, Keywords: []string{"typeform"}, CaseInsensitive: true},
	{ID: "todoist-api-token", Category: "todoist", Title: "Todoist API token", Pattern: `(?:todoist[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:)[\s'"]{0,3}([0-9a-f]{40})`, Keywords: []string{"todoist"}, CaseInsensitive: true},
	{ID: "openai-api-key", Category: "openai", Title: "OpenAI API Key", Pattern: `(sk-[a-zA-Z0-9]{50})`, Keywords: []string{"sk-"}},
	{ID: "openai-api-key-project", Category: "openai", Title: "OpenAI Project-scoped API Key", Pattern: `(sk-proj-[A-Za-z0-9]{24}-[A-Za-z0-9]{40,128})`, CaseInsensitive: true, Keywords: []string{"sk-proj-"}},
	{ID: "openai-api-key-env", Category: "openai", Title: "OpenAI Environment-scoped API Key", Pattern: `(sk-(?:live|test)-[A-Za-z0-9]{24}-[A-Za-z0-9]{40,128})`, CaseInsensitive: true, Keywords: []string{"sk-live-", "sk-test-"}},
	{ID: "anthropic-api-key", Category: "anthropic", Title: "Anthropic API Key", Pattern: `(sk-ant-([a-zA-Z0-9]{1,10}-)?[a-zA-Z0-9_-]{32,128})`, Keywords: []string{"sk-ant-"}},
	{ID: "canva-token", Category: "canva", Title: "Canva Token", Pattern: `\b(cnv[a-z0-9]{2}[A-Za-z0-9_=-]+[a-f0-9]{8})\b`, Keywords: []string{"cnv"}},
	{ID: "sk-secret", Category: "unknown", Title: "Unknown SK Secret", Pattern: `(?:^|['"\s])(sk(?:[-_][a-z0-9]{1,10})?[-_][a-z0-9]{10,99})(?:$|['"\s])`, CaseInsensitive: true, Keywords: []string{"sk-", "sk_"}},
	{ID: "api-key", Category: "unknown", Title: "Unknown API Key", Pattern: `(?:[a-z0-9_ .,-]{0,25}api[-_](?:key|token)(?:\S{0,5}))\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?([a-z0-9+/_\-]{6,128})['"]?(?=\s|$|[;,\]})'"])`, Keywords: []string{"api-key", "api_key", "api-token", "api_token"}, CaseInsensitive: true, ExcludeWords: []string{"api", "key", "secret", "foo", "example", "dummy", "password", "12345", "abcde", "placeholder", "fake", "token"}},
	{ID: "webhook-secret", Category: "unknown", Title: "Unknown Webhook Secret", Pattern: `(?:[a-z0-9_ .,-]{0,25}webhook[-_]secret(?:\S{0,5}))\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?([a-z0-9+/=\-]{6,128})['"]?(?=\s|$|[;,\]})'"])`, Keywords: []string{"webhook-secret", "webhook_secret"}, CaseInsensitive: true, ExcludeWords: []string{"api", "key", "secret", "foo", "example", "dummy", "password", "12345", "abcde", "placeholder", "fake", "token", "webhook"}},
	{ID: "password", Category: "unknown", Title: "Unknown Password", Pattern: `(?:[a-z0-9_ .,-]{0,25}password(?:\S{0,5}))\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?([a-z0-9+/=\-]{6,128})['"]?(?=\s|$|[;,\]})'"])`, Keywords: []string{"password"}, CaseInsensitive: true, ExcludeWords: []string{"api", "key", "secret", "foo", "example", "dummy", "string", "password", "12345", "abcde", "placeholder", "fake", "token", "pass", "pwd"}},
	{ID: "secret-value", Category: "unknown", Title: "Unknown Secret Value", Pattern: `(?:[a-z0-9_ .,-]{0,25}[-_](?:secret)(?:\S{0,5}))\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?([a-z0-9+/=\-]{6,128})['"]?(?=\s|$|[;,\]})'"])`, Keywords: []string{"secret"}, CaseInsensitive: true, ExcludeWords: []string{"api", "key", "secret", "foo", "example", "dummy", "password", "12345", "abcde", "placeholder", "fake", "token"}},
}
