// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCheckpointFileStmt, err = db.PrepareContext(ctx, addCheckpointFile); err != nil {
		return nil, fmt.Errorf("error preparing query AddCheckpointFile: %w", err)
	}
	if q.appendMemoryEventStmt, err = db.PrepareContext(ctx, appendMemoryEvent); err != nil {
		return nil, fmt.Errorf("error preparing query AppendMemoryEvent: %w", err)
	}
	if q.countCheckpointFilesStmt, err = db.PrepareContext(ctx, countCheckpointFiles); err != nil {
		return nil, fmt.Errorf("error preparing query CountCheckpointFiles: %w", err)
	}
	if q.countMessagesBySessionStmt, err = db.PrepareContext(ctx, countMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountMessagesBySession: %w", err)
	}
	if q.createCheckpointStmt, err = db.PrepareContext(ctx, createCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCheckpoint: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMemoryJobStmt, err = db.PrepareContext(ctx, createMemoryJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMemoryJob: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteCheckpointStmt, err = db.PrepareContext(ctx, deleteCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCheckpoint: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMCPOAuthTokenStmt, err = db.PrepareContext(ctx, deleteMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPOAuthToken: %w", err)
	}
	if q.deleteMCPToolCacheStmt, err = db.PrepareContext(ctx, deleteMCPToolCache); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPToolCache: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionCheckpointsStmt, err = db.PrepareContext(ctx, deleteSessionCheckpoints); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionCheckpoints: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getCheckpointStmt, err = db.PrepareContext(ctx, getCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckpoint: %w", err)
	}
	if q.getCheckpointByMessageIDStmt, err = db.PrepareContext(ctx, getCheckpointByMessageID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckpointByMessageID: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getLatestSessionCheckpointStmt, err = db.PrepareContext(ctx, getLatestSessionCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestSessionCheckpoint: %w", err)
	}
	if q.getMCPOAuthTokenStmt, err = db.PrepareContext(ctx, getMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetMCPOAuthToken: %w", err)
	}
	if q.getMCPToolCacheStmt, err = db.PrepareContext(ctx, getMCPToolCache); err != nil {
		return nil, fmt.Errorf("error preparing query GetMCPToolCache: %w", err)
	}
	if q.getMaterializedViewStmt, err = db.PrepareContext(ctx, getMaterializedView); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaterializedView: %w", err)
	}
	if q.getMaxMemoryEventWatermarkStmt, err = db.PrepareContext(ctx, getMaxMemoryEventWatermark); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxMemoryEventWatermark: %w", err)
	}
	if q.getMemoryEventByIDStmt, err = db.PrepareContext(ctx, getMemoryEventByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemoryEventByID: %w", err)
	}
	if q.getMemorySourceByNameStmt, err = db.PrepareContext(ctx, getMemorySourceByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemorySourceByName: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listCheckpointFilesStmt, err = db.PrepareContext(ctx, listCheckpointFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListCheckpointFiles: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMaterializedViewsStmt, err = db.PrepareContext(ctx, listMaterializedViews); err != nil {
		return nil, fmt.Errorf("error preparing query ListMaterializedViews: %w", err)
	}
	if q.listMemoryEventsByWatermarkStmt, err = db.PrepareContext(ctx, listMemoryEventsByWatermark); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoryEventsByWatermark: %w", err)
	}
	if q.listMemoryEventsFilteredStmt, err = db.PrepareContext(ctx, listMemoryEventsFiltered); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoryEventsFiltered: %w", err)
	}
	if q.listMemoryJobsByStatusStmt, err = db.PrepareContext(ctx, listMemoryJobsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoryJobsByStatus: %w", err)
	}
	if q.listMemorySourcesStmt, err = db.PrepareContext(ctx, listMemorySources); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemorySources: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesBySessionPageStmt, err = db.PrepareContext(ctx, listMessagesBySessionPage); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionPage: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listRecentMemoryJobsStmt, err = db.PrepareContext(ctx, listRecentMemoryJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentMemoryJobs: %w", err)
	}
	if q.listSessionCheckpointsStmt, err = db.PrepareContext(ctx, listSessionCheckpoints); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionCheckpoints: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listSessionsByParentIDStmt, err = db.PrepareContext(ctx, listSessionsByParentID); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsByParentID: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.resetMaterializedViewWatermarkStmt, err = db.PrepareContext(ctx, resetMaterializedViewWatermark); err != nil {
		return nil, fmt.Errorf("error preparing query ResetMaterializedViewWatermark: %w", err)
	}
	if q.searchMessagesStmt, err = db.PrepareContext(ctx, searchMessages); err != nil {
		return nil, fmt.Errorf("error preparing query SearchMessages: %w", err)
	}
	if q.updateMemoryJobStatusStmt, err = db.PrepareContext(ctx, updateMemoryJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemoryJobStatus: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionCollaborationModeStmt, err = db.PrepareContext(ctx, updateSessionCollaborationMode); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionCollaborationMode: %w", err)
	}
	if q.updateSessionPermissionModeStmt, err = db.PrepareContext(ctx, updateSessionPermissionMode); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionPermissionMode: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	if q.upsertMCPOAuthTokenStmt, err = db.PrepareContext(ctx, upsertMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMCPOAuthToken: %w", err)
	}
	if q.upsertMCPToolCacheStmt, err = db.PrepareContext(ctx, upsertMCPToolCache); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMCPToolCache: %w", err)
	}
	if q.upsertMaterializedViewStmt, err = db.PrepareContext(ctx, upsertMaterializedView); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMaterializedView: %w", err)
	}
	if q.upsertMemorySourceStmt, err = db.PrepareContext(ctx, upsertMemorySource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMemorySource: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCheckpointFileStmt != nil {
		if cerr := q.addCheckpointFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCheckpointFileStmt: %w", cerr)
		}
	}
	if q.appendMemoryEventStmt != nil {
		if cerr := q.appendMemoryEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing appendMemoryEventStmt: %w", cerr)
		}
	}
	if q.countCheckpointFilesStmt != nil {
		if cerr := q.countCheckpointFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCheckpointFilesStmt: %w", cerr)
		}
	}
	if q.countMessagesBySessionStmt != nil {
		if cerr := q.countMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.createCheckpointStmt != nil {
		if cerr := q.createCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCheckpointStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMemoryJobStmt != nil {
		if cerr := q.createMemoryJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMemoryJobStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteCheckpointStmt != nil {
		if cerr := q.deleteCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCheckpointStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMCPOAuthTokenStmt != nil {
		if cerr := q.deleteMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPOAuthTokenStmt: %w", cerr)
		}
	}
	if q.deleteMCPToolCacheStmt != nil {
		if cerr := q.deleteMCPToolCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPToolCacheStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionCheckpointsStmt != nil {
		if cerr := q.deleteSessionCheckpointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionCheckpointsStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getCheckpointStmt != nil {
		if cerr := q.getCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckpointStmt: %w", cerr)
		}
	}
	if q.getCheckpointByMessageIDStmt != nil {
		if cerr := q.getCheckpointByMessageIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckpointByMessageIDStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getLatestSessionCheckpointStmt != nil {
		if cerr := q.getLatestSessionCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestSessionCheckpointStmt: %w", cerr)
		}
	}
	if q.getMCPOAuthTokenStmt != nil {
		if cerr := q.getMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMCPOAuthTokenStmt: %w", cerr)
		}
	}
	if q.getMCPToolCacheStmt != nil {
		if cerr := q.getMCPToolCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMCPToolCacheStmt: %w", cerr)
		}
	}
	if q.getMaterializedViewStmt != nil {
		if cerr := q.getMaterializedViewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaterializedViewStmt: %w", cerr)
		}
	}
	if q.getMaxMemoryEventWatermarkStmt != nil {
		if cerr := q.getMaxMemoryEventWatermarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxMemoryEventWatermarkStmt: %w", cerr)
		}
	}
	if q.getMemoryEventByIDStmt != nil {
		if cerr := q.getMemoryEventByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoryEventByIDStmt: %w", cerr)
		}
	}
	if q.getMemorySourceByNameStmt != nil {
		if cerr := q.getMemorySourceByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemorySourceByNameStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listCheckpointFilesStmt != nil {
		if cerr := q.listCheckpointFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCheckpointFilesStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMaterializedViewsStmt != nil {
		if cerr := q.listMaterializedViewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMaterializedViewsStmt: %w", cerr)
		}
	}
	if q.listMemoryEventsByWatermarkStmt != nil {
		if cerr := q.listMemoryEventsByWatermarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoryEventsByWatermarkStmt: %w", cerr)
		}
	}
	if q.listMemoryEventsFilteredStmt != nil {
		if cerr := q.listMemoryEventsFilteredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoryEventsFilteredStmt: %w", cerr)
		}
	}
	if q.listMemoryJobsByStatusStmt != nil {
		if cerr := q.listMemoryJobsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoryJobsByStatusStmt: %w", cerr)
		}
	}
	if q.listMemorySourcesStmt != nil {
		if cerr := q.listMemorySourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemorySourcesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionPageStmt != nil {
		if cerr := q.listMessagesBySessionPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionPageStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listRecentMemoryJobsStmt != nil {
		if cerr := q.listRecentMemoryJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentMemoryJobsStmt: %w", cerr)
		}
	}
	if q.listSessionCheckpointsStmt != nil {
		if cerr := q.listSessionCheckpointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionCheckpointsStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsByParentIDStmt != nil {
		if cerr := q.listSessionsByParentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsByParentIDStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.resetMaterializedViewWatermarkStmt != nil {
		if cerr := q.resetMaterializedViewWatermarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetMaterializedViewWatermarkStmt: %w", cerr)
		}
	}
	if q.searchMessagesStmt != nil {
		if cerr := q.searchMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchMessagesStmt: %w", cerr)
		}
	}
	if q.updateMemoryJobStatusStmt != nil {
		if cerr := q.updateMemoryJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemoryJobStatusStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionCollaborationModeStmt != nil {
		if cerr := q.updateSessionCollaborationModeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionCollaborationModeStmt: %w", cerr)
		}
	}
	if q.updateSessionPermissionModeStmt != nil {
		if cerr := q.updateSessionPermissionModeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionPermissionModeStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.upsertMCPOAuthTokenStmt != nil {
		if cerr := q.upsertMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMCPOAuthTokenStmt: %w", cerr)
		}
	}
	if q.upsertMCPToolCacheStmt != nil {
		if cerr := q.upsertMCPToolCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMCPToolCacheStmt: %w", cerr)
		}
	}
	if q.upsertMaterializedViewStmt != nil {
		if cerr := q.upsertMaterializedViewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMaterializedViewStmt: %w", cerr)
		}
	}
	if q.upsertMemorySourceStmt != nil {
		if cerr := q.upsertMemorySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMemorySourceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	addCheckpointFileStmt              *sql.Stmt
	appendMemoryEventStmt              *sql.Stmt
	countCheckpointFilesStmt           *sql.Stmt
	countMessagesBySessionStmt         *sql.Stmt
	createCheckpointStmt               *sql.Stmt
	createFileStmt                     *sql.Stmt
	createMemoryJobStmt                *sql.Stmt
	createMessageStmt                  *sql.Stmt
	createSessionStmt                  *sql.Stmt
	deleteCheckpointStmt               *sql.Stmt
	deleteFileStmt                     *sql.Stmt
	deleteMCPOAuthTokenStmt            *sql.Stmt
	deleteMCPToolCacheStmt             *sql.Stmt
	deleteMessageStmt                  *sql.Stmt
	deleteSessionStmt                  *sql.Stmt
	deleteSessionCheckpointsStmt       *sql.Stmt
	deleteSessionFilesStmt             *sql.Stmt
	deleteSessionMessagesStmt          *sql.Stmt
	getAverageResponseTimeStmt         *sql.Stmt
	getCheckpointStmt                  *sql.Stmt
	getCheckpointByMessageIDStmt       *sql.Stmt
	getFileStmt                        *sql.Stmt
	getFileByPathAndSessionStmt        *sql.Stmt
	getFileReadStmt                    *sql.Stmt
	getHourDayHeatmapStmt              *sql.Stmt
	getLastSessionStmt                 *sql.Stmt
	getLatestSessionCheckpointStmt     *sql.Stmt
	getMCPOAuthTokenStmt               *sql.Stmt
	getMCPToolCacheStmt                *sql.Stmt
	getMaterializedViewStmt            *sql.Stmt
	getMaxMemoryEventWatermarkStmt     *sql.Stmt
	getMemoryEventByIDStmt             *sql.Stmt
	getMemorySourceByNameStmt          *sql.Stmt
	getMessageStmt                     *sql.Stmt
	getRecentActivityStmt              *sql.Stmt
	getSessionByIDStmt                 *sql.Stmt
	getToolUsageStmt                   *sql.Stmt
	getTotalStatsStmt                  *sql.Stmt
	getUsageByDayStmt                  *sql.Stmt
	getUsageByDayOfWeekStmt            *sql.Stmt
	getUsageByHourStmt                 *sql.Stmt
	getUsageByModelStmt                *sql.Stmt
	listAllUserMessagesStmt            *sql.Stmt
	listCheckpointFilesStmt            *sql.Stmt
	listFilesByPathStmt                *sql.Stmt
	listFilesBySessionStmt             *sql.Stmt
	listLatestSessionFilesStmt         *sql.Stmt
	listMaterializedViewsStmt          *sql.Stmt
	listMemoryEventsByWatermarkStmt    *sql.Stmt
	listMemoryEventsFilteredStmt       *sql.Stmt
	listMemoryJobsByStatusStmt         *sql.Stmt
	listMemorySourcesStmt              *sql.Stmt
	listMessagesBySessionStmt          *sql.Stmt
	listMessagesBySessionPageStmt      *sql.Stmt
	listNewFilesStmt                   *sql.Stmt
	listRecentMemoryJobsStmt           *sql.Stmt
	listSessionCheckpointsStmt         *sql.Stmt
	listSessionReadFilesStmt           *sql.Stmt
	listSessionsStmt                   *sql.Stmt
	listSessionsByParentIDStmt         *sql.Stmt
	listUserMessagesBySessionStmt      *sql.Stmt
	recordFileReadStmt                 *sql.Stmt
	renameSessionStmt                  *sql.Stmt
	resetMaterializedViewWatermarkStmt *sql.Stmt
	searchMessagesStmt                 *sql.Stmt
	updateMemoryJobStatusStmt          *sql.Stmt
	updateMessageStmt                  *sql.Stmt
	updateSessionStmt                  *sql.Stmt
	updateSessionCollaborationModeStmt *sql.Stmt
	updateSessionPermissionModeStmt    *sql.Stmt
	updateSessionTitleAndUsageStmt     *sql.Stmt
	upsertMCPOAuthTokenStmt            *sql.Stmt
	upsertMCPToolCacheStmt             *sql.Stmt
	upsertMaterializedViewStmt         *sql.Stmt
	upsertMemorySourceStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		addCheckpointFileStmt:              q.addCheckpointFileStmt,
		appendMemoryEventStmt:              q.appendMemoryEventStmt,
		countCheckpointFilesStmt:           q.countCheckpointFilesStmt,
		countMessagesBySessionStmt:         q.countMessagesBySessionStmt,
		createCheckpointStmt:               q.createCheckpointStmt,
		createFileStmt:                     q.createFileStmt,
		createMemoryJobStmt:                q.createMemoryJobStmt,
		createMessageStmt:                  q.createMessageStmt,
		createSessionStmt:                  q.createSessionStmt,
		deleteCheckpointStmt:               q.deleteCheckpointStmt,
		deleteFileStmt:                     q.deleteFileStmt,
		deleteMCPOAuthTokenStmt:            q.deleteMCPOAuthTokenStmt,
		deleteMCPToolCacheStmt:             q.deleteMCPToolCacheStmt,
		deleteMessageStmt:                  q.deleteMessageStmt,
		deleteSessionStmt:                  q.deleteSessionStmt,
		deleteSessionCheckpointsStmt:       q.deleteSessionCheckpointsStmt,
		deleteSessionFilesStmt:             q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:          q.deleteSessionMessagesStmt,
		getAverageResponseTimeStmt:         q.getAverageResponseTimeStmt,
		getCheckpointStmt:                  q.getCheckpointStmt,
		getCheckpointByMessageIDStmt:       q.getCheckpointByMessageIDStmt,
		getFileStmt:                        q.getFileStmt,
		getFileByPathAndSessionStmt:        q.getFileByPathAndSessionStmt,
		getFileReadStmt:                    q.getFileReadStmt,
		getHourDayHeatmapStmt:              q.getHourDayHeatmapStmt,
		getLastSessionStmt:                 q.getLastSessionStmt,
		getLatestSessionCheckpointStmt:     q.getLatestSessionCheckpointStmt,
		getMCPOAuthTokenStmt:               q.getMCPOAuthTokenStmt,
		getMCPToolCacheStmt:                q.getMCPToolCacheStmt,
		getMaterializedViewStmt:            q.getMaterializedViewStmt,
		getMaxMemoryEventWatermarkStmt:     q.getMaxMemoryEventWatermarkStmt,
		getMemoryEventByIDStmt:             q.getMemoryEventByIDStmt,
		getMemorySourceByNameStmt:          q.getMemorySourceByNameStmt,
		getMessageStmt:                     q.getMessageStmt,
		getRecentActivityStmt:              q.getRecentActivityStmt,
		getSessionByIDStmt:                 q.getSessionByIDStmt,
		getToolUsageStmt:                   q.getToolUsageStmt,
		getTotalStatsStmt:                  q.getTotalStatsStmt,
		getUsageByDayStmt:                  q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:            q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:                 q.getUsageByHourStmt,
		getUsageByModelStmt:                q.getUsageByModelStmt,
		listAllUserMessagesStmt:            q.listAllUserMessagesStmt,
		listCheckpointFilesStmt:            q.listCheckpointFilesStmt,
		listFilesByPathStmt:                q.listFilesByPathStmt,
		listFilesBySessionStmt:             q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:         q.listLatestSessionFilesStmt,
		listMaterializedViewsStmt:          q.listMaterializedViewsStmt,
		listMemoryEventsByWatermarkStmt:    q.listMemoryEventsByWatermarkStmt,
		listMemoryEventsFilteredStmt:       q.listMemoryEventsFilteredStmt,
		listMemoryJobsByStatusStmt:         q.listMemoryJobsByStatusStmt,
		listMemorySourcesStmt:              q.listMemorySourcesStmt,
		listMessagesBySessionStmt:          q.listMessagesBySessionStmt,
		listMessagesBySessionPageStmt:      q.listMessagesBySessionPageStmt,
		listNewFilesStmt:                   q.listNewFilesStmt,
		listRecentMemoryJobsStmt:           q.listRecentMemoryJobsStmt,
		listSessionCheckpointsStmt:         q.listSessionCheckpointsStmt,
		listSessionReadFilesStmt:           q.listSessionReadFilesStmt,
		listSessionsStmt:                   q.listSessionsStmt,
		listSessionsByParentIDStmt:         q.listSessionsByParentIDStmt,
		listUserMessagesBySessionStmt:      q.listUserMessagesBySessionStmt,
		recordFileReadStmt:                 q.recordFileReadStmt,
		renameSessionStmt:                  q.renameSessionStmt,
		resetMaterializedViewWatermarkStmt: q.resetMaterializedViewWatermarkStmt,
		searchMessagesStmt:                 q.searchMessagesStmt,
		updateMemoryJobStatusStmt:          q.updateMemoryJobStatusStmt,
		updateMessageStmt:                  q.updateMessageStmt,
		updateSessionStmt:                  q.updateSessionStmt,
		updateSessionCollaborationModeStmt: q.updateSessionCollaborationModeStmt,
		updateSessionPermissionModeStmt:    q.updateSessionPermissionModeStmt,
		updateSessionTitleAndUsageStmt:     q.updateSessionTitleAndUsageStmt,
		upsertMCPOAuthTokenStmt:            q.upsertMCPOAuthTokenStmt,
		upsertMCPToolCacheStmt:             q.upsertMCPToolCacheStmt,
		upsertMaterializedViewStmt:         q.upsertMaterializedViewStmt,
		upsertMemorySourceStmt:             q.upsertMemorySourceStmt,
	}
}
