// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_oauth_tokens.sql

package db

import (
	"context"
	"database/sql"
)

const deleteMCPOAuthToken = `-- name: DeleteMCPOAuthToken :exec
DELETE FROM mcp_oauth_tokens
WHERE server_name = ?
`

func (q *Queries) DeleteMCPOAuthToken(ctx context.Context, serverName string) error {
	_, err := q.exec(ctx, q.deleteMCPOAuthTokenStmt, deleteMCPOAuthToken, serverName)
	return err
}

const getMCPOAuthToken = `-- name: GetMCPOAuthToken :one
SELECT server_name, access_token, refresh_token, expires_at, created_at, updated_at FROM mcp_oauth_tokens
WHERE server_name = ?
`

func (q *Queries) GetMCPOAuthToken(ctx context.Context, serverName string) (McpOauthToken, error) {
	row := q.queryRow(ctx, q.getMCPOAuthTokenStmt, getMCPOAuthToken, serverName)
	var i McpOauthToken
	err := row.Scan(
		&i.ServerName,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPOAuthToken = `-- name: UpsertMCPOAuthToken :exec
INSERT INTO mcp_oauth_tokens (server_name, access_token, refresh_token, expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(server_name) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    expires_at = excluded.expires_at,
    updated_at = strftime('%s','now')
`

type UpsertMCPOAuthTokenParams struct {
	ServerName   string        `json:"server_name"`
	AccessToken  string        `json:"access_token"`
	RefreshToken string        `json:"refresh_token"`
	ExpiresAt    sql.NullInt64 `json:"expires_at"`
}

func (q *Queries) UpsertMCPOAuthToken(ctx context.Context, arg UpsertMCPOAuthTokenParams) error {
	_, err := q.exec(ctx, q.upsertMCPOAuthTokenStmt, upsertMCPOAuthToken,
		arg.ServerName,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
