// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_tool_cache.sql

package db

import (
	"context"
)

const deleteMCPToolCache = `-- name: DeleteMCPToolCache :exec
DELETE FROM mcp_tool_cache
WHERE server_name = ?
`

func (q *Queries) DeleteMCPToolCache(ctx context.Context, serverName string) error {
	_, err := q.exec(ctx, q.deleteMCPToolCacheStmt, deleteMCPToolCache, serverName)
	return err
}

const getMCPToolCache = `-- name: GetMCPToolCache :one
SELECT server_name, config_hash, tools_json, cached_at FROM mcp_tool_cache
WHERE server_name = ?
`

func (q *Queries) GetMCPToolCache(ctx context.Context, serverName string) (McpToolCache, error) {
	row := q.queryRow(ctx, q.getMCPToolCacheStmt, getMCPToolCache, serverName)
	var i McpToolCache
	err := row.Scan(
		&i.ServerName,
		&i.ConfigHash,
		&i.ToolsJson,
		&i.CachedAt,
	)
	return i, err
}

const upsertMCPToolCache = `-- name: UpsertMCPToolCache :exec
INSERT INTO mcp_tool_cache (server_name, config_hash, tools_json)
VALUES (?, ?, ?)
ON CONFLICT(server_name) DO UPDATE SET
    config_hash = excluded.config_hash,
    tools_json = excluded.tools_json,
    cached_at = strftime('%s','now')
`

type UpsertMCPToolCacheParams struct {
	ServerName string `json:"server_name"`
	ConfigHash string `json:"config_hash"`
	ToolsJson  string `json:"tools_json"`
}

func (q *Queries) UpsertMCPToolCache(ctx context.Context, arg UpsertMCPToolCacheParams) error {
	_, err := q.exec(ctx, q.upsertMCPToolCacheStmt, upsertMCPToolCache, arg.ServerName, arg.ConfigHash, arg.ToolsJson)
	return err
}
