// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package db

import (
	"context"
	"database/sql"
)

const appendMemoryEvent = `-- name: AppendMemoryEvent :exec
INSERT OR IGNORE INTO memory_events (
    id, session_id, scope, kind, content, summary, source_json, source_hash,
    confidence, importance, supersedes, tags_json, watermark, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    COALESCE((SELECT MAX(watermark) FROM memory_events) + 1, 1), ?, ?
)
`

type AppendMemoryEventParams struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Scope      string         `json:"scope"`
	Kind       string         `json:"kind"`
	Content    string         `json:"content"`
	Summary    string         `json:"summary"`
	SourceJson string         `json:"source_json"`
	SourceHash string         `json:"source_hash"`
	Confidence float64        `json:"confidence"`
	Importance float64        `json:"importance"`
	Supersedes sql.NullString `json:"supersedes"`
	TagsJson   string         `json:"tags_json"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) AppendMemoryEvent(ctx context.Context, arg AppendMemoryEventParams) error {
	_, err := q.exec(ctx, q.appendMemoryEventStmt, appendMemoryEvent,
		arg.ID,
		arg.SessionID,
		arg.Scope,
		arg.Kind,
		arg.Content,
		arg.Summary,
		arg.SourceJson,
		arg.SourceHash,
		arg.Confidence,
		arg.Importance,
		arg.Supersedes,
		arg.TagsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMemoryJob = `-- name: CreateMemoryJob :exec
INSERT INTO memory_jobs (id, job_type, status, owner, lease_expires_at, retry_count, max_retries, payload_json, error_message, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMemoryJobParams struct {
	ID             string        `json:"id"`
	JobType        string        `json:"job_type"`
	Status         string        `json:"status"`
	Owner          string        `json:"owner"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
	RetryCount     int64         `json:"retry_count"`
	MaxRetries     int64         `json:"max_retries"`
	PayloadJson    string        `json:"payload_json"`
	ErrorMessage   string        `json:"error_message"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
}

func (q *Queries) CreateMemoryJob(ctx context.Context, arg CreateMemoryJobParams) error {
	_, err := q.exec(ctx, q.createMemoryJobStmt, createMemoryJob,
		arg.ID,
		arg.JobType,
		arg.Status,
		arg.Owner,
		arg.LeaseExpiresAt,
		arg.RetryCount,
		arg.MaxRetries,
		arg.PayloadJson,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getMaterializedView = `-- name: GetMaterializedView :one
SELECT id, view_name, watermark, schema_version, created_at, updated_at
FROM memory_materialized_views
WHERE view_name = ?
`

func (q *Queries) GetMaterializedView(ctx context.Context, viewName string) (MemoryMaterializedView, error) {
	row := q.queryRow(ctx, q.getMaterializedViewStmt, getMaterializedView, viewName)
	var i MemoryMaterializedView
	err := row.Scan(
		&i.ID,
		&i.ViewName,
		&i.Watermark,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxMemoryEventWatermark = `-- name: GetMaxMemoryEventWatermark :one
SELECT COALESCE(MAX(watermark), 0) FROM memory_events
`

func (q *Queries) GetMaxMemoryEventWatermark(ctx context.Context) (interface{}, error) {
	row := q.queryRow(ctx, q.getMaxMemoryEventWatermarkStmt, getMaxMemoryEventWatermark)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getMemoryEventByID = `-- name: GetMemoryEventByID :one
SELECT id, session_id, scope, kind, content, summary, source_json, source_hash,
       confidence, importance, supersedes, tags_json, watermark, created_at, updated_at
FROM memory_events
WHERE id = ?
`

type GetMemoryEventByIDRow struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Scope      string         `json:"scope"`
	Kind       string         `json:"kind"`
	Content    string         `json:"content"`
	Summary    string         `json:"summary"`
	SourceJson string         `json:"source_json"`
	SourceHash string         `json:"source_hash"`
	Confidence float64        `json:"confidence"`
	Importance float64        `json:"importance"`
	Supersedes sql.NullString `json:"supersedes"`
	TagsJson   string         `json:"tags_json"`
	Watermark  int64          `json:"watermark"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) GetMemoryEventByID(ctx context.Context, id string) (GetMemoryEventByIDRow, error) {
	row := q.queryRow(ctx, q.getMemoryEventByIDStmt, getMemoryEventByID, id)
	var i GetMemoryEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Scope,
		&i.Kind,
		&i.Content,
		&i.Summary,
		&i.SourceJson,
		&i.SourceHash,
		&i.Confidence,
		&i.Importance,
		&i.Supersedes,
		&i.TagsJson,
		&i.Watermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemorySourceByName = `-- name: GetMemorySourceByName :one
SELECT id, name, source_type, cursor, last_processed_message_id, watermark, created_at, updated_at
FROM memory_sources
WHERE name = ?
`

func (q *Queries) GetMemorySourceByName(ctx context.Context, name string) (MemorySource, error) {
	row := q.queryRow(ctx, q.getMemorySourceByNameStmt, getMemorySourceByName, name)
	var i MemorySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Cursor,
		&i.LastProcessedMessageID,
		&i.Watermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterializedViews = `-- name: ListMaterializedViews :many
SELECT id, view_name, watermark, schema_version, created_at, updated_at
FROM memory_materialized_views
ORDER BY view_name
`

func (q *Queries) ListMaterializedViews(ctx context.Context) ([]MemoryMaterializedView, error) {
	rows, err := q.query(ctx, q.listMaterializedViewsStmt, listMaterializedViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryMaterializedView{}
	for rows.Next() {
		var i MemoryMaterializedView
		if err := rows.Scan(
			&i.ID,
			&i.ViewName,
			&i.Watermark,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEventsByWatermark = `-- name: ListMemoryEventsByWatermark :many
SELECT id, session_id, scope, kind, content, summary, source_json, source_hash,
       confidence, importance, supersedes, tags_json, watermark, created_at, updated_at
FROM memory_events
WHERE watermark > ?
ORDER BY watermark ASC
LIMIT ?
`

type ListMemoryEventsByWatermarkParams struct {
	Watermark int64 `json:"watermark"`
	Limit     int64 `json:"limit"`
}

type ListMemoryEventsByWatermarkRow struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Scope      string         `json:"scope"`
	Kind       string         `json:"kind"`
	Content    string         `json:"content"`
	Summary    string         `json:"summary"`
	SourceJson string         `json:"source_json"`
	SourceHash string         `json:"source_hash"`
	Confidence float64        `json:"confidence"`
	Importance float64        `json:"importance"`
	Supersedes sql.NullString `json:"supersedes"`
	TagsJson   string         `json:"tags_json"`
	Watermark  int64          `json:"watermark"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) ListMemoryEventsByWatermark(ctx context.Context, arg ListMemoryEventsByWatermarkParams) ([]ListMemoryEventsByWatermarkRow, error) {
	rows, err := q.query(ctx, q.listMemoryEventsByWatermarkStmt, listMemoryEventsByWatermark, arg.Watermark, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoryEventsByWatermarkRow{}
	for rows.Next() {
		var i ListMemoryEventsByWatermarkRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.Summary,
			&i.SourceJson,
			&i.SourceHash,
			&i.Confidence,
			&i.Importance,
			&i.Supersedes,
			&i.TagsJson,
			&i.Watermark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEventsFiltered = `-- name: ListMemoryEventsFiltered :many
SELECT id, session_id, scope, kind, content, summary, source_json, source_hash,
       confidence, importance, supersedes, tags_json, watermark, created_at, updated_at
FROM memory_events
WHERE watermark > ?
  AND (?
    = '' OR scope = ?)
  AND (?
    = '' OR kind = ?)
  AND (? = 0 OR created_at >= ?)
  AND (? = 0 OR created_at < ?)
ORDER BY watermark ASC
LIMIT ?
`

type ListMemoryEventsFilteredParams struct {
	Watermark   int64       `json:"watermark"`
	Column2     interface{} `json:"column_2"`
	Scope       string      `json:"scope"`
	Column4     interface{} `json:"column_4"`
	Kind        string      `json:"kind"`
	Column6     interface{} `json:"column_6"`
	CreatedAt   int64       `json:"created_at"`
	Column8     interface{} `json:"column_8"`
	CreatedAt_2 int64       `json:"created_at_2"`
	Limit       int64       `json:"limit"`
}

type ListMemoryEventsFilteredRow struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Scope      string         `json:"scope"`
	Kind       string         `json:"kind"`
	Content    string         `json:"content"`
	Summary    string         `json:"summary"`
	SourceJson string         `json:"source_json"`
	SourceHash string         `json:"source_hash"`
	Confidence float64        `json:"confidence"`
	Importance float64        `json:"importance"`
	Supersedes sql.NullString `json:"supersedes"`
	TagsJson   string         `json:"tags_json"`
	Watermark  int64          `json:"watermark"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) ListMemoryEventsFiltered(ctx context.Context, arg ListMemoryEventsFilteredParams) ([]ListMemoryEventsFilteredRow, error) {
	rows, err := q.query(ctx, q.listMemoryEventsFilteredStmt, listMemoryEventsFiltered,
		arg.Watermark,
		arg.Column2,
		arg.Scope,
		arg.Column4,
		arg.Kind,
		arg.Column6,
		arg.CreatedAt,
		arg.Column8,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoryEventsFilteredRow{}
	for rows.Next() {
		var i ListMemoryEventsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.Summary,
			&i.SourceJson,
			&i.SourceHash,
			&i.Confidence,
			&i.Importance,
			&i.Supersedes,
			&i.TagsJson,
			&i.Watermark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryJobsByStatus = `-- name: ListMemoryJobsByStatus :many
SELECT id, job_type, status, owner, lease_expires_at, retry_count, max_retries, payload_json, error_message, created_at, updated_at
FROM memory_jobs
WHERE status = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMemoryJobsByStatus(ctx context.Context, status string) ([]MemoryJob, error) {
	rows, err := q.query(ctx, q.listMemoryJobsByStatusStmt, listMemoryJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryJob{}
	for rows.Next() {
		var i MemoryJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.Owner,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.PayloadJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemorySources = `-- name: ListMemorySources :many
SELECT id, name, source_type, cursor, last_processed_message_id, watermark, created_at, updated_at
FROM memory_sources
ORDER BY name
`

func (q *Queries) ListMemorySources(ctx context.Context) ([]MemorySource, error) {
	rows, err := q.query(ctx, q.listMemorySourcesStmt, listMemorySources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemorySource{}
	for rows.Next() {
		var i MemorySource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Cursor,
			&i.LastProcessedMessageID,
			&i.Watermark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemoryJobs = `-- name: ListRecentMemoryJobs :many
SELECT id, job_type, status, owner, lease_expires_at, retry_count, max_retries, payload_json, error_message, created_at, updated_at
FROM memory_jobs
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentMemoryJobs(ctx context.Context, limit int64) ([]MemoryJob, error) {
	rows, err := q.query(ctx, q.listRecentMemoryJobsStmt, listRecentMemoryJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryJob{}
	for rows.Next() {
		var i MemoryJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.Owner,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.PayloadJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMaterializedViewWatermark = `-- name: ResetMaterializedViewWatermark :exec
UPDATE memory_materialized_views
SET watermark = 0, updated_at = ?
WHERE view_name = ?
`

type ResetMaterializedViewWatermarkParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ViewName  string `json:"view_name"`
}

func (q *Queries) ResetMaterializedViewWatermark(ctx context.Context, arg ResetMaterializedViewWatermarkParams) error {
	_, err := q.exec(ctx, q.resetMaterializedViewWatermarkStmt, resetMaterializedViewWatermark, arg.UpdatedAt, arg.ViewName)
	return err
}

const updateMemoryJobStatus = `-- name: UpdateMemoryJobStatus :exec
UPDATE memory_jobs
SET status = ?, owner = ?, lease_expires_at = ?, retry_count = ?, error_message = ?, updated_at = ?
WHERE id = ?
`

type UpdateMemoryJobStatusParams struct {
	Status         string        `json:"status"`
	Owner          string        `json:"owner"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
	RetryCount     int64         `json:"retry_count"`
	ErrorMessage   string        `json:"error_message"`
	UpdatedAt      int64         `json:"updated_at"`
	ID             string        `json:"id"`
}

func (q *Queries) UpdateMemoryJobStatus(ctx context.Context, arg UpdateMemoryJobStatusParams) error {
	_, err := q.exec(ctx, q.updateMemoryJobStatusStmt, updateMemoryJobStatus,
		arg.Status,
		arg.Owner,
		arg.LeaseExpiresAt,
		arg.RetryCount,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertMaterializedView = `-- name: UpsertMaterializedView :exec
INSERT INTO memory_materialized_views (id, view_name, watermark, schema_version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(view_name) DO UPDATE SET
    watermark = excluded.watermark,
    schema_version = excluded.schema_version,
    updated_at = excluded.updated_at
`

type UpsertMaterializedViewParams struct {
	ID            string `json:"id"`
	ViewName      string `json:"view_name"`
	Watermark     int64  `json:"watermark"`
	SchemaVersion int64  `json:"schema_version"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertMaterializedView(ctx context.Context, arg UpsertMaterializedViewParams) error {
	_, err := q.exec(ctx, q.upsertMaterializedViewStmt, upsertMaterializedView,
		arg.ID,
		arg.ViewName,
		arg.Watermark,
		arg.SchemaVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertMemorySource = `-- name: UpsertMemorySource :exec
INSERT INTO memory_sources (id, name, source_type, cursor, last_processed_message_id, watermark, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    cursor = excluded.cursor,
    last_processed_message_id = excluded.last_processed_message_id,
    watermark = excluded.watermark,
    updated_at = excluded.updated_at
`

type UpsertMemorySourceParams struct {
	ID                     string `json:"id"`
	Name                   string `json:"name"`
	SourceType             string `json:"source_type"`
	Cursor                 string `json:"cursor"`
	LastProcessedMessageID string `json:"last_processed_message_id"`
	Watermark              int64  `json:"watermark"`
	CreatedAt              int64  `json:"created_at"`
	UpdatedAt              int64  `json:"updated_at"`
}

func (q *Queries) UpsertMemorySource(ctx context.Context, arg UpsertMemorySourceParams) error {
	_, err := q.exec(ctx, q.upsertMemorySourceStmt, upsertMemorySource,
		arg.ID,
		arg.Name,
		arg.SourceType,
		arg.Cursor,
		arg.LastProcessedMessageID,
		arg.Watermark,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
