// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Checkpoint struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
	CreatedAt int64  `json:"created_at"`
}

type CheckpointFile struct {
	CheckpointID string `json:"checkpoint_id"`
	FileID       string `json:"file_id"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type MemoryEvent struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Scope      string         `json:"scope"`
	Kind       string         `json:"kind"`
	Content    string         `json:"content"`
	Summary    string         `json:"summary"`
	SourceJson string         `json:"source_json"`
	SourceHash string         `json:"source_hash"`
	Confidence float64        `json:"confidence"`
	Importance float64        `json:"importance"`
	Supersedes sql.NullString `json:"supersedes"`
	TagsJson   string         `json:"tags_json"`
	Watermark  int64          `json:"watermark"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	ExpiresAt  sql.NullInt64  `json:"expires_at"`
}

type MemoryEventsFt struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	Summary string `json:"summary"`
	Scope   string `json:"scope"`
	Kind    string `json:"kind"`
	Tags    string `json:"tags"`
}

type MemoryJob struct {
	ID             string        `json:"id"`
	JobType        string        `json:"job_type"`
	Status         string        `json:"status"`
	Owner          string        `json:"owner"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
	RetryCount     int64         `json:"retry_count"`
	MaxRetries     int64         `json:"max_retries"`
	PayloadJson    string        `json:"payload_json"`
	ErrorMessage   string        `json:"error_message"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
}

type MemoryMaterializedView struct {
	ID            string `json:"id"`
	ViewName      string `json:"view_name"`
	Watermark     int64  `json:"watermark"`
	SchemaVersion int64  `json:"schema_version"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type MemorySource struct {
	ID                     string `json:"id"`
	Name                   string `json:"name"`
	SourceType             string `json:"source_type"`
	Cursor                 string `json:"cursor"`
	LastProcessedMessageID string `json:"last_processed_message_id"`
	Watermark              int64  `json:"watermark"`
	CreatedAt              int64  `json:"created_at"`
	UpdatedAt              int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	ReasoningTokens  int64          `json:"reasoning_tokens"`
	CacheReadTokens  int64          `json:"cache_read_tokens"`
	CacheWriteTokens int64          `json:"cache_write_tokens"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID                     string         `json:"id"`
	ParentSessionID        sql.NullString `json:"parent_session_id"`
	Title                  string         `json:"title"`
	MessageCount           int64          `json:"message_count"`
	PromptTokens           int64          `json:"prompt_tokens"`
	CompletionTokens       int64          `json:"completion_tokens"`
	Cost                   float64        `json:"cost"`
	UpdatedAt              int64          `json:"updated_at"`
	CreatedAt              int64          `json:"created_at"`
	SummaryMessageID       sql.NullString `json:"summary_message_id"`
	Todos                  sql.NullString `json:"todos"`
	CollaborationMode      string         `json:"collaboration_mode"`
	LastPromptTokens       int64          `json:"last_prompt_tokens"`
	LastCompletionTokens   int64          `json:"last_completion_tokens"`
	WorkspaceCwd           sql.NullString `json:"workspace_cwd"`
	Kind                   string         `json:"kind"`
	HandoffSourceSessionID sql.NullString `json:"handoff_source_session_id"`
	HandoffGoal            string         `json:"handoff_goal"`
	HandoffDraftPrompt     string         `json:"handoff_draft_prompt"`
	HandoffRelevantFiles   string         `json:"handoff_relevant_files"`
	PermissionMode         string         `json:"permission_mode"`
	LastSummaryAt          sql.NullInt64  `json:"last_summary_at"`
}
