// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    workspace_cwd,
    collaboration_mode,
    permission_mode,
    kind,
    handoff_source_session_id,
    handoff_goal,
    handoff_draft_prompt,
    handoff_relevant_files,
    plan_file_path,
    goal_id,
    goal_text,
    goal_status,
    goal_token_budget,
    goal_tokens_used,
    goal_time_seconds,
    goal_created_at,
    goal_updated_at,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type CreateSessionParams struct {
	ID                     string         `json:"id"`
	ParentSessionID        sql.NullString `json:"parent_session_id"`
	Title                  string         `json:"title"`
	WorkspaceCwd           sql.NullString `json:"workspace_cwd"`
	CollaborationMode      string         `json:"collaboration_mode"`
	PermissionMode         string         `json:"permission_mode"`
	Kind                   string         `json:"kind"`
	HandoffSourceSessionID sql.NullString `json:"handoff_source_session_id"`
	HandoffGoal            string         `json:"handoff_goal"`
	HandoffDraftPrompt     string         `json:"handoff_draft_prompt"`
	HandoffRelevantFiles   string         `json:"handoff_relevant_files"`
	PlanFilePath           string         `json:"plan_file_path"`
	GoalID                 string         `json:"goal_id"`
	GoalText               string         `json:"goal_text"`
	GoalStatus             string         `json:"goal_status"`
	GoalTokenBudget        int64          `json:"goal_token_budget"`
	GoalTokensUsed         int64          `json:"goal_tokens_used"`
	GoalTimeSeconds        int64          `json:"goal_time_seconds"`
	GoalCreatedAt          int64          `json:"goal_created_at"`
	GoalUpdatedAt          int64          `json:"goal_updated_at"`
	MessageCount           int64          `json:"message_count"`
	PromptTokens           int64          `json:"prompt_tokens"`
	CompletionTokens       int64          `json:"completion_tokens"`
	Cost                   float64        `json:"cost"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.WorkspaceCwd,
		arg.CollaborationMode,
		arg.PermissionMode,
		arg.Kind,
		arg.HandoffSourceSessionID,
		arg.HandoffGoal,
		arg.HandoffDraftPrompt,
		arg.HandoffRelevantFiles,
		arg.PlanFilePath,
		arg.GoalID,
		arg.GoalText,
		arg.GoalStatus,
		arg.GoalTokenBudget,
		arg.GoalTokensUsed,
		arg.GoalTimeSeconds,
		arg.GoalCreatedAt,
		arg.GoalUpdatedAt,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
FROM sessions
WHERE parent_session_id IS NULL
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
FROM sessions
WHERE parent_session_id is NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.CollaborationMode,
			&i.LastPromptTokens,
			&i.LastCompletionTokens,
			&i.WorkspaceCwd,
			&i.Kind,
			&i.HandoffSourceSessionID,
			&i.HandoffGoal,
			&i.HandoffDraftPrompt,
			&i.HandoffRelevantFiles,
			&i.PermissionMode,
			&i.LastSummaryAt,
			&i.PlanFilePath,
			&i.GoalText,
			&i.GoalStatus,
			&i.GoalTokenBudget,
			&i.GoalTokensUsed,
			&i.GoalTimeSeconds,
			&i.GoalCreatedAt,
			&i.GoalUpdatedAt,
			&i.GoalID,
			&i.Archived,
			&i.Pinned,
			&i.InferenceConfig,
			&i.InferenceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByParentID = `-- name: ListSessionsByParentID :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
FROM sessions
WHERE parent_session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByParentID(ctx context.Context, parentSessionID sql.NullString) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsByParentIDStmt, listSessionsByParentID, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.CollaborationMode,
			&i.LastPromptTokens,
			&i.LastCompletionTokens,
			&i.WorkspaceCwd,
			&i.Kind,
			&i.HandoffSourceSessionID,
			&i.HandoffGoal,
			&i.HandoffDraftPrompt,
			&i.HandoffRelevantFiles,
			&i.PermissionMode,
			&i.LastSummaryAt,
			&i.PlanFilePath,
			&i.GoalText,
			&i.GoalStatus,
			&i.GoalTokenBudget,
			&i.GoalTokensUsed,
			&i.GoalTimeSeconds,
			&i.GoalCreatedAt,
			&i.GoalUpdatedAt,
			&i.GoalID,
			&i.Archived,
			&i.Pinned,
			&i.InferenceConfig,
			&i.InferenceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :one
UPDATE sessions
SET
    title = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const setSessionArchived = `-- name: SetSessionArchived :one
UPDATE sessions
SET archived = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type SetSessionArchivedParams struct {
	Archived int64  `json:"archived"`
	ID       string `json:"id"`
}

func (q *Queries) SetSessionArchived(ctx context.Context, arg SetSessionArchivedParams) (Session, error) {
	row := q.queryRow(ctx, q.setSessionArchivedStmt, setSessionArchived, arg.Archived, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const setSessionPinned = `-- name: SetSessionPinned :one
UPDATE sessions
SET pinned = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type SetSessionPinnedParams struct {
	Pinned int64  `json:"pinned"`
	ID     string `json:"id"`
}

func (q *Queries) SetSessionPinned(ctx context.Context, arg SetSessionPinnedParams) (Session, error) {
	row := q.queryRow(ctx, q.setSessionPinnedStmt, setSessionPinned, arg.Pinned, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    workspace_cwd = ?,
    collaboration_mode = ?,
    permission_mode = ?,
    kind = ?,
    handoff_source_session_id = ?,
    handoff_goal = ?,
    handoff_draft_prompt = ?,
    handoff_relevant_files = ?,
    plan_file_path = ?,
    goal_id = ?,
    goal_text = ?,
    goal_status = ?,
    goal_token_budget = ?,
    goal_tokens_used = ?,
    goal_time_seconds = ?,
    goal_created_at = ?,
    goal_updated_at = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    last_prompt_tokens = ?,
    last_completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    todos = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionParams struct {
	Title                  string         `json:"title"`
	WorkspaceCwd           sql.NullString `json:"workspace_cwd"`
	CollaborationMode      string         `json:"collaboration_mode"`
	PermissionMode         string         `json:"permission_mode"`
	Kind                   string         `json:"kind"`
	HandoffSourceSessionID sql.NullString `json:"handoff_source_session_id"`
	HandoffGoal            string         `json:"handoff_goal"`
	HandoffDraftPrompt     string         `json:"handoff_draft_prompt"`
	HandoffRelevantFiles   string         `json:"handoff_relevant_files"`
	PlanFilePath           string         `json:"plan_file_path"`
	GoalID                 string         `json:"goal_id"`
	GoalText               string         `json:"goal_text"`
	GoalStatus             string         `json:"goal_status"`
	GoalTokenBudget        int64          `json:"goal_token_budget"`
	GoalTokensUsed         int64          `json:"goal_tokens_used"`
	GoalTimeSeconds        int64          `json:"goal_time_seconds"`
	GoalCreatedAt          int64          `json:"goal_created_at"`
	GoalUpdatedAt          int64          `json:"goal_updated_at"`
	PromptTokens           int64          `json:"prompt_tokens"`
	CompletionTokens       int64          `json:"completion_tokens"`
	LastPromptTokens       int64          `json:"last_prompt_tokens"`
	LastCompletionTokens   int64          `json:"last_completion_tokens"`
	SummaryMessageID       sql.NullString `json:"summary_message_id"`
	Cost                   float64        `json:"cost"`
	Todos                  sql.NullString `json:"todos"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.WorkspaceCwd,
		arg.CollaborationMode,
		arg.PermissionMode,
		arg.Kind,
		arg.HandoffSourceSessionID,
		arg.HandoffGoal,
		arg.HandoffDraftPrompt,
		arg.HandoffRelevantFiles,
		arg.PlanFilePath,
		arg.GoalID,
		arg.GoalText,
		arg.GoalStatus,
		arg.GoalTokenBudget,
		arg.GoalTokensUsed,
		arg.GoalTimeSeconds,
		arg.GoalCreatedAt,
		arg.GoalUpdatedAt,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.LastPromptTokens,
		arg.LastCompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSessionCollaborationMode = `-- name: UpdateSessionCollaborationMode :one
UPDATE sessions
SET collaboration_mode = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionCollaborationModeParams struct {
	CollaborationMode string `json:"collaboration_mode"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateSessionCollaborationMode(ctx context.Context, arg UpdateSessionCollaborationModeParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionCollaborationModeStmt, updateSessionCollaborationMode, arg.CollaborationMode, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSessionInferenceConfig = `-- name: UpdateSessionInferenceConfig :one
UPDATE sessions
SET
    inference_config = ?,
    inference_revision = inference_revision + 1
WHERE id = ? AND inference_revision = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionInferenceConfigParams struct {
	InferenceConfig   string `json:"inference_config"`
	ID                string `json:"id"`
	InferenceRevision int64  `json:"inference_revision"`
}

func (q *Queries) UpdateSessionInferenceConfig(ctx context.Context, arg UpdateSessionInferenceConfigParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionInferenceConfigStmt, updateSessionInferenceConfig, arg.InferenceConfig, arg.ID, arg.InferenceRevision)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSessionPermissionMode = `-- name: UpdateSessionPermissionMode :one
UPDATE sessions
SET permission_mode = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionPermissionModeParams struct {
	PermissionMode string `json:"permission_mode"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionPermissionModeStmt, updateSessionPermissionMode, arg.PermissionMode, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSessionPlanFilePath = `-- name: UpdateSessionPlanFilePath :one
UPDATE sessions
SET plan_file_path = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionPlanFilePathParams struct {
	PlanFilePath string `json:"plan_file_path"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSessionPlanFilePath(ctx context.Context, arg UpdateSessionPlanFilePathParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionPlanFilePathStmt, updateSessionPlanFilePath, arg.PlanFilePath, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, collaboration_mode, last_prompt_tokens, last_completion_tokens, workspace_cwd, kind, handoff_source_session_id, handoff_goal, handoff_draft_prompt, handoff_relevant_files, permission_mode, last_summary_at, plan_file_path, goal_text, goal_status, goal_token_budget, goal_tokens_used, goal_time_seconds, goal_created_at, goal_updated_at, goal_id, archived, pinned, inference_config, inference_revision
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CollaborationMode,
		&i.LastPromptTokens,
		&i.LastCompletionTokens,
		&i.WorkspaceCwd,
		&i.Kind,
		&i.HandoffSourceSessionID,
		&i.HandoffGoal,
		&i.HandoffDraftPrompt,
		&i.HandoffRelevantFiles,
		&i.PermissionMode,
		&i.LastSummaryAt,
		&i.PlanFilePath,
		&i.GoalText,
		&i.GoalStatus,
		&i.GoalTokenBudget,
		&i.GoalTokensUsed,
		&i.GoalTimeSeconds,
		&i.GoalCreatedAt,
		&i.GoalUpdatedAt,
		&i.GoalID,
		&i.Archived,
		&i.Pinned,
		&i.InferenceConfig,
		&i.InferenceRevision,
	)
	return i, err
}
